name: client
publish_to: none

environment:
  sdk: ^3.2.5

dependencies:
  drift: ^2.15.0
  http: ^1.2.0
  shared:
    path: ../shared/

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  drift_dev: ^2.15.0
  build_runner: ^2.4.8
